"""removed measurement/design column

Revision ID: eefa37c1357a
Revises: 
Create Date: 2025-02-17 18:21:35.352948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eefa37c1357a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_item', 'design')
    op.drop_column('order_item', 'measurement')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_item', sa.Column('measurement', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('order_item', sa.Column('design', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
